<?php
$beats = [
    'Toxz - Forever_98BPM',
    'Toxz - Clash Of Natives_75BPM',
    'Toxz - Father And Son_75BPM',
    'Toxz - Game Changer_70BPM',
    'Toxz - Don\'t Stop_89BPM',
    'Toxz - Adriano_85BPM',
    'Toxz - Turtle Funk_63BPM',
    'Toxz - Heisenberger_84BPM',
    'Toxz - Big City Scratch_85BPM',
    'Toxz - Diamonty_86BPM',
    'Toxz - Electric Smoke_120BPM',
    'Toxz - Mosquito_84BPM',
    'Toxz - Internet Rock_86BPM',
    'Toxz - Sugar Brown_88BPM',
    'Toxz - Keep It Low_68BPM',
    'Toxz - Milky Clouds_89BPM',
    'Toxz - Ganxta Bitch_74BPM',
    'Toxz - Devastated_50BPM',
    'Toxz - Criminal Minded_95BPM',
    'Toxz - Strings On Acid_88BPM',
    'Toxz - Altered Beast_86BPM',
    'Toxz - No Pain No Gain_116BPM',
    'Toxz - Blood From The Sky_85BPM',
    'Toxz - Grab The Stick_88BPM',
    'Toxz - Hard Guitar_97BPM',
    'Toxz - Oreo Dust_73BPM',
    'Toxz - Like A Ghost_97BPM',
    'Toxz - Team Up The Crew_93BPM',
    'Toxz - Gladiator_86BPM',
    'Toxz - Fight For Might_89BPM',
    'Toxz - Don\'t Mess With The East_100BPM',
    'Toxz - Vergiss Damals_78BPM',
    'Toxz - Baby Doll_84BPM',
    'Toxz - Chipmunk Anthem_94BPM',
    'Toxz - Will Wieder Leben_75BPM',
    'Toxz - Hurt Locker_89BPM',
    'Toxz - Splash The Party Pool_96BPM',
    'Toxz - For The Old Ones_112BPM',
    'Toxz - Es Wird Blut Geben_87BPM',
    'Toxz - Saxocut_88BPM',
    'Toxz - The New Beginning_86BPM',
    'Toxz - Want It All_92BPM',
    'Toxz - Ready For The End_90BPM',
    'Toxz - Ghettofeuer_105BPM',
    'Toxz - Leave This Town_83BPM',
    'Toxz - Juggler_88BPM',
    'Toxz - Back To School_93BPM',
    'Toxz - Beach Assault_120BPM',
    'Toxz - Red Light Bitches_100BPM',
    'Toxz - Jazzy Funky_60BPM',
    'Toxz - Desert Safari_82BPM',
    'Toxz - Die Eisernen Hanteln_124BPM',
    'Toxz - Life Is A Broken Dream_89BPM',
    'Toxz - New Drunken Flat_86BPM',
    'Toxz - Girl Holla_107BPM',
    'Toxz - Glockenturm Rave_88BPM',
    'Toxz - Work Dat_91BPM',
    'Toxz - Music For Kingz_77BPM',
    'Toxz - Dear Hip Hop_87BPM',
    'Toxz - We Are Masters_84BPM',
    'Toxz - Bring The Notes_96BPM',
    'Toxz - Cyborg Wars_92BPM',
    'Toxz - Let\'s Get Naked_120BPM',
    'Toxz - Bone Rider_97BPM',
    'Toxz - Foggy Roads_86BPM',
    'Toxz - Cold Faces_83BPM',
    'Toxz - Hamburg Remix_71BPM',
    'Toxz - Fire_60BPM',
    'Toxz - The Return_89BPM',
    'Toxz - Get Up For A New World_85BPM',
    'Toxz - Graveyard Bouncer_91BPM',
    'Toxz - Krom_87BPM',
    'Toxz - Lands Of Hope_97BPM',
    'Toxz - Poker Ass_82BPM',
    'Toxz - Berlin Deep_120BPM',
    'Toxz - Parsec Contest_140BPM',
    'Toxz - Orgel_84BPM',
    'Toxz - Unicorn_102BPM',
    'Toxz - Ride The Boards_65BPM',
    'Toxz - Fick Die Stadt_84BPM',
    'Toxz - Stand Up_97BPM',
    'Toxz - 30-205-FKS_91BPM',
    'Toxz - Piano Dreams_87BPM',
    'Toxz - In Der Kirche_90BPM',
    'Toxz - Doom_95BPM',
    'Toxz - Just Another Battle_92BPM',
    'Toxz - Dein Style Ist Crazy_90BPM',
    'Toxz - Skies Of Love_89BPM',
    'Toxz - Der Kleine Trompeter_89BPM',
    'Toxz - What The Fuck_125BPM',
    'Toxz - Destroy Everything_86BPM',
    'Toxz - Mosh Rooms_87BPM',
    'Toxz - Orientblüte_89BPM',
    'Toxz - Drunken Funker_90BPM',
    'Toxz - Dub Siren_82BPM',
    'Toxz - Auf Den Punkt_100BPM',
    'Toxz - Cherry Popper_82BPM',
    'Toxz - Knall Den Scheiss_120BPM',
    'Toxz - Nicht Von Dieser Welt_92BPM',
    'Toxz - This Is How We Do_109BPM',
    'Toxz - Freaks With No Future_113BPM',
    'Toxz - Freaks At Work_83BPM',
    'Toxz - Crazy Brains_87BPM',
    'Toxz - Kellergroove_68BPM',
    'Toxz - Be Quiet_81BPM',
    'Toxz - Fag Fluter_94BPM',
    'Toxz - Bounce_96BPM',
    'Toxz - New Year_107BPM',
    'Toxz - The Warrior_93BPM',
    'Toxz - Monstersound_94BPM',
    'Toxz - Fat Beatzn_105BPM',
    'Toxz - Autoknacker_106BPM',
    'Toxz - Toxic Waste Outro_109BPM',
    'Toxz - Saxy Stomp_92BPM',
    'Toxz - This Is My Year_86BPM',
    'Toxz - Gabba Hop_88BPM',
    'Toxz - Bongo Bomber_86BPM',
    'Toxz - Alone And Free_107BPM',
    'Toxz - The Real Baseliner_90BPM',
    'Toxz - Hot Like Fire_85BPM',
    'Toxz - Respektlose Nacht_88BPM',
    'Toxz - Killer\'s Day_58BPM',
    'Toxz - Acid Bowle_84BPM',
    'Toxz - Bloody Roar_87BPM',
    'Toxz - Psychoman_88BPM',
    'Toxz - Back Im Business_80BPM',
    'Toxz - Outer World_90BPM',
    'Toxz - Heavy Trip_86BPM',
    'Toxz - Einleitung_93BPM',
    'Toxz - Knietief_86BPM',
    'Toxz - Thug Life_89BPM',
    'Toxz - Feel The Summer_125BPM',
    'Toxz - Total Destruction_89BPM',
    'Toxz - Roll Something_88BPM',
    'Toxz - Backjump_89BPM',
    'Toxz - Fantasy Land_88BPM',
    'Toxz - Night Rider_90BPM',
    'Toxz - Tunnelblick_95BPM',
    'Toxz - Technohit_135BPM',
    'Toxz - Eat It Raw_116BPM',
    'Toxz - Angels From Hell_86BPM',
    'Toxz - It\'s Gonna Rain_90BPM',
    'Toxz - Rausschmeisser_89BPM',
    'Toxz - Waiting For Something Else_89BPM',
    'Toxz - Allein Unter 1000_90BPM',
    'Toxz - Mr. Brooks_88BPM',
    'Toxz - Think Twice_83BPM',
    'Toxz - Grauer Beton_97BPM',
    'Toxz - Track An Gott_87BPM',
    'Toxz - Party With The 205_105BPM',
    'Toxz - Chill Down The Universe_92BPM',
    'Toxz - Kelly_77BPM',
    'Toxz - Excited About Nothing_90BPM',
    'Toxz - Return Of The Hardest_87BPM',
    'Toxz - Fuck Da Master_96BPM',
    'Toxz - Dope 4 Hope_88BPM',
    'Toxz - High Lines_93BPM',
    'Toxz - Holy Shit Kicks_94BPM',
    'Toxz - Bomb The Bank_79BPM',
    'Toxz - Ragga_89BPM',
    'Toxz - Hardliner_93BPM',
    'Toxz - Scheiss Drauf_83BPM',
    'Toxz - Notorious_87BPM',
    'Toxz - Dark Business_87BPM',
    'Toxz - Bloodsport_87BPM',
    'Toxz - Geigensmasher_89BPM',
    'Toxz - Check Em Out_90BPM',
    'Toxz - Recyclinghof_96BPM',
    'Toxz - Back In Da Days_77BPM',
    'Toxz - Orchestrator_90BPM',
    'Toxz - Children_76BPM',
    'Toxz - My Life_91BPM',
    'Toxz - New Era_70BPM',
    'Toxz - Blow The Horns Bitch_93BPM',
    'Toxz - Chop Rott_89BPM',
    'Toxz - Yeah_89BPM',
    'Toxz - Einfach Boom_92BPM',
    'Toxz - Get Retarded_94BPM',
    'Toxz - Stoned Raiders_87BPM',
    'Toxz - Zitronenbaum_104BPM',
    'Toxz - Zigarettenpause_96BPM',
    'Toxz - Crazy Shit_87BPM',
    'Toxz - My Lady_73BPM',
    'Toxz - Kill All Humans_104BPM',
    'Toxz - Stiff Piano Riffs_95BPM',
    'Toxz - It\'s Time_89BPM',
    'Toxz - Ghettoboys_88BPM',
    'Toxz - Rolex_90BPM',
    'Toxz - Dead Skulls_95BPM',
    'Toxz - Fresh_96BPM',
    'Toxz - Party People_92BPM',
    'Toxz - Deathchamber 612_112BPM',
    'Toxz - Funky Force_110BPM',
    'Toxz - Fuck Your Sister_135BPM',
    'Toxz - Harter Tobak_95BPM',
    'Toxz - Airwolf_120BPM',
    'Toxz - Engel Der Nacht_97BPM',
    'Toxz - Streeters_87BPM',
    'Toxz - Fantasy Love_71BPM',
    'Toxz - Indianer_89BPM',
    'Toxz - Synthie Burner_77BPM',
    'Toxz - Mindless Mashup_125BPM',
    'Toxz - Kill The Racks_92BPM',
    'Toxz - Glocken Und So_92BPM',
    'Toxz - Get That Money_62BPM',
    'Toxz - Soul Calibur_110BPM',
    'Toxz - Street Fighter Battle_106BPM',
    'Toxz - Tetris_140BPM',
    'Toxz - Streetlife On Drugs_88BPM',
    'Toxz - Work Hard_95BPM',
    'Toxz - Start From Scratch_86BPM',
    'Toxz - Reanimator_96BPM',
    'Toxz - 2UPs_97BPM',
    'Toxz - The Green Planet_140BPM',
    'Toxz - Backyard Rave_150BPM',
    'Toxz - The 90ies Dance_130BPM',
    'Toxz - Pump It Up_140BPM',
    'Toxz - Zulu Warrior_94BPM',
    'Toxz - Long Live The Kim_95BPM',
    'Toxz - Elektronigans_100BPM',
    'Toxz - The Master Is In The House_93BPM',
    'Toxz - Funky Lover_83BPM',
    'Toxz - Psycho_91BPM',
    'Toxz - Here I Go Again_135BPM',
    'Toxz - Far Away_86BPM',
    'Toxz - Macheten_95BPM',
    'Toxz - Rocking Beats_94BPM',
    'Toxz - Monsterhit_95BPM',
    'Toxz - Orient Xpress_89BPM',
    'Toxz - Mary In Love_80BPM',
    'Toxz - ILD_90BPM',
    'Toxz - Watch Dis_125BPM',
    'Toxz - Transmission Controllers_92BPM',
    'Toxz - Fuck All Living Things_96BPM',
    'Toxz - Jet Set_124BPM',
    'Toxz - Orientleiche_95BPM',
    'Toxz - Fat Boys_86BPM',
    'Toxz - Allein Zu Zweit_94BPM',
    'Toxz - Super Blower_88BPM',
    'Toxz - Dat Fuck_140BPM',
    'Toxz - Housy Patterns_130BPM',
    'Toxz - School\'s Out_100BPM',
    'Toxz - Kalte Zeiten_65BPM',
    'Toxz - Only A Dream_102BPM',
    'Toxz - Turn It Up_105BPM',
    'Toxz - Far Away From Love_82BPM',
    'Toxz - Think About It_70BPM',
    'Toxz - Leave This World_95BPM',
    'Toxz - Trauerspiel_88BPM',
    'Toxz - Banging Flipper_95BPM',
    'Toxz - Deep Pink Holes_93BPM',
    'Toxz - The U The B The S_95BPM',
    'Toxz - Flute Destroyer_95BPM',
    'Toxz - Graffiti Terroristen_90BPM',
    'Toxz - Toeten_89BPM',
    'Toxz - Mystery_95BPM',
    'Toxz - I Wanna Call You_98BPM',
    'Toxz - The End Is Near_90BPM',
    'Toxz - Where Is She_88BPM',
    'Toxz - Baguette Greek Beat_88BPM',
    'Toxz - Morgens Um Halb Zwei_95BPM',
    'Toxz - Remember Me (Remix)_120BPM',
    'Toxz - Pull Up To The Bumper (Remix)_120BPM',
    'Toxz - Ready Or Not (Remix)_174BPM',
    'Toxz - Street Dreams (Remix)_100BPM',
    'Toxz - Berlin Berlin (Remix)_125BPM',
    'Toxz - Holiday Mixtape 2005',
    'Toxz - Back In Time Turntable Mini Mix',
    'Hassler & Player - Champagne Mixtape',
    'Battle Of The Beats Mixtape Vol. 1',
    'Battle Of The Beats Mixtape Vol. 2'
];